language: node_js
node_js:
  - 10
  - 12
  - 14

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn test --coverage

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: kcyYmRhGaB2vERoXi1XBGihY45tLqUQ6sakOMbBPGmoyV3Txw+sO7wE405w0COq5aXqmnZg86shJm2yLqLV7TwYHDc285vGtLWyGZ/saV8bxml1lF8qiWLHplcw4ilVJLU8rOIbOR0hTdUbyIv9jWRGWloIwadtaX7wWDBPJfAEcuNcFusgb3GXoGCjlk5k9BYUOH39HAPVcQlN9n1cWs++aHTWx9C0ulpmP8vMm1Ht2wAyv28vjq9wZSCgI8Yu0XSXQQUIZyGXIdTzZjwOrpdzu+51QgG3Av5EXlpBzCPFcfrnH0r0SryaqbHXV33NPU8qXUjuK2SfiX6cp+JQ8seRMTevynZ+8Yt5usbK2Pp37c+ylAj5rXC8FPVRifi51oItMwnu4QYktqbMbWDIMkgcBm3u5icxiZOw5e9SLUATe7jUTWrAEoLL7ssefLdKFo4AJXWXxozf1+5BqsU3vAaWeLygQ3kUE07V9Iu9Guc58LDmkh4nICSXbNt+EmuT7Br4GmtYHG9qpXniHOcy9IMWLHjONMJXTO40RHcWYCofeKatiwgH4C9BJjnbETifWIp+qIVwjASetCOs2gokTD24VQYG8scRbEyhJNAYVhl+5wfYcoX4o2mGs0mVONArUUFY5gw5sqIXgAFhB2KdK3o8ltHtzPR0Z/l4B9/kPV6I=
  skip_cleanup: true
  on:
    tags: true
    repo: Turbo87/auto-dist-tag
